version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    ports:
      - "80:80"
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    ports:
      - "8890:8890"
    restart: "no"
  migrations:
    restart: "no"
  resource:
    restart: "no"
