version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  frontend:
    restart: "no"
  identifier:
    ports:
      - "80:80"
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  delta-notifier:
    restart: "no"
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  migrations:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  search:
    environment:
      LOG_LEVEL: "debug"
    restart: "no"
  elasticsearch:
    restart: "no"
  file:
    restart: "no"
  publication-consumer:
    environment:
      LOG_SPARQL_ALL: "true"
      DEBUG_AUTH_HEADERS: "true"
    restart: "no"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    volumes:
      - ./config/search:/search
    ports:
      - 5601:5601
    userns_mode: "host"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    restart: "no"

