version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    restart: "no"
    ports:
      - "80:80"
  dispatcher:
    restart: "no"
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  database:
    restart: "no"
  migrations:
    restart: "no"
  resource:
    restart: "no"
  search:
    environment:
      LOG_LEVEL: "debug"
    restart: "no"
    ports:
      - "8888:80"
  elasticsearch:
    restart: "no"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    volumes:
      - ./config/mu-elastic-search:/search
    ports:
      - 5601:5601
    userns_mode: "host"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    restart: "no"
