PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?mandataris <http://mu.semte.ch/vocabularies/ext/activeStatus> "inactive" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?mandataris a mandaat:Mandataris .
    FILTER NOT EXISTS { ?mandataris <http://mu.semte.ch/vocabularies/ext/activeStatus> ?status . }
  }
}











