(define-resource document ()
  :class (s-prefix "foaf:Document")
  :properties `((:title                 :string ,(s-prefix "dct:title")))
  :has-many `((document-version         :via ,(s-prefix "besluitvorming:heeftVersie")
                                        :as "document-versions"))
  :has-one `((document-type             :via ,(s-prefix "ext:documentType")
                                        :as "type"))
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/documenten/")
  :features '(include-uri)
  :on-path "documents")

(define-resource document-version ()
  :class (s-prefix "ext:DocumentVersie")
  :properties `((:version-number        :string   ,(s-prefix "ext:versieNummer")))
  :has-one `((file                      :via      ,(s-prefix "ext:file")
                                        :as "file")
            (document                   :via      ,(s-prefix "besluitvorming:heeftVersie")
                                        :inverse t
                                        :as "document"))
  :has-many `((newsletter-info      :via    ,(s-prefix "ext:documentVersie")
                                    :inverse t
                                    :as "news-items"))
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/document-versies/")
  :features `(include-uri)
  :on-path "document-versions")

(define-resource document-type ()
  :class (s-prefix "ext:DocumentTypeCode")
  :properties `((:label             :string ,(s-prefix "skos:prefLabel"))
                (:alt-label         :string ,(s-prefix "skos:altLabel")))
  :has-many `((document             :via    ,(s-prefix "ext:documentType")
                                    :inverse t
                                    :as "documents")
              (document-type        :via    ,(s-prefix "skos:broader")
                                    :inverse t
                                    :as "subtypes"))
  :has-one `((document-type         :via    ,(s-prefix "skos:broader")
                                    :as "supertype"))
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/concept/document-type-codes/")
  :features '(include-uri)
  :on-path "document-types")

