(define-resource document-container()
  :class (s-prefix "dossier:Serie")
  :has-many `((document                 :via ,(s-prefix "dossier:collectie.bestaatUit")
                                        :as "document-versions"))
  :has-one `((document-type             :via ,(s-prefix "ext:documentType")
                                        :as "type"))
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/series/")
  :features '(include-uri)
  :on-path "document-containers")

(define-resource document()
  :class (s-prefix "dossier:Stuk")
  :properties `((:title                 :string   ,(s-prefix "dct:title")))
  :has-one `((file                      :via      ,(s-prefix "ext:file")
                                        :as "file")
            (file                       :via      ,(s-prefix "ext:convertedFile")
                                        :as "converted-file")
            (document-container         :via      ,(s-prefix "dossier:collectie.bestaatUit")
                                        :inverse t
                                        :as "document"))
  :has-many `((newsletter-info      :via    ,(s-prefix "ext:documentVersie")
                                    :inverse t
                                    :as "news-items"))
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/documenten/")
  :features `(include-uri)
  :on-path "documents")

(define-resource document-type ()
  :class (s-prefix "ext:DocumentTypeCode")
  :properties `((:label             :string ,(s-prefix "skos:prefLabel"))
                (:alt-label         :string ,(s-prefix "skos:altLabel")))
  :has-many `((document-container            :via    ,(s-prefix "ext:documentType")
                                    :inverse t
                                    :as "documents")
              (document-type        :via    ,(s-prefix "skos:broader")
                                    :inverse t
                                    :as "subtypes"))
  :has-one `((document-type         :via    ,(s-prefix "skos:broader")
                                    :as "supertype"))
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/concept/document-type-codes/")
  :features '(include-uri)
  :on-path "document-types")
